name: "Tests"

on:
  push:
  schedule:
    - cron: '0 16 * * *'

jobs:
  compatibility:
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: symfony
          MYSQL_DATABASE: symfony_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: symfony
          POSTGRES_DB: symfony_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    name: "Tests"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        symfony:
          - '7.4.*'
          - '8.0.*'
        persistence:
          - '3.4.*'
          - '4.1.*'
        exclude:
          -   php-version: "8.2"
              symfony: '8.0.*'
          -   php-version: "8.3"
              symfony: '8.0.*'
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: pdo_sqlite, pdo_mysql, pdo_pgsql, zlib, bz2, zip, zstd, lz4
          ini-values: memory_limit=-1
          coverage: pcov

      - name: Stop pre-installed MySQL
        run: sudo /etc/init.d/mysql stop


      - name: Configure Symfony
        run: composer config extra.symfony.require "${{ matrix.symfony }}"

      - name: Configure Doctrine Persistence
        run: composer require "doctrine/persistence:${{ matrix.persistence }}" --no-update --no-interaction

      - name: Install symfony/var-exporter for Doctrine Persistence 3.4
        if: matrix.persistence == '3.4.*'
        run: composer require "symfony/var-exporter" --no-interaction

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Cache dependencies"
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-

      - name: "Install highest dependencies"
        run: |
          composer global require php-coveralls/php-coveralls
          composer update --no-interaction --no-progress --no-suggest

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DATABASE_URL: mysql://root:symfony@127.0.0.1:3306/symfony_test?serverVersion=8.0
          DATABASE_POSTGRES_URL: postgresql://postgres:symfony@127.0.0.1:5432/symfony_test?serverVersion=15.0
          SYMFONY_PHPUNIT_VERSION: "12"
        run: vendor/bin/phpunit --coverage-clover build/reports/clover.xml

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          php-coveralls --coverage_clover=build/reports/clover.xml --json_path=build/reports/coveralls-upload.json -v
        continue-on-error: true
