name: "Tests"

on:
  push:
  schedule:
    - cron: '0 16 * * *'

jobs:
  compatibility:
    name: "Tests"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        symfony:
          - '7.4.*'
          - '8.0.*'
        exclude:
          -   php-version: "8.2"
              symfony: '8.0.*'
          -   php-version: "8.3"
              symfony: '8.0.*'
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: pdo_sqlite, zlib, bz2, zip, zstd, lz4
          ini-values: memory_limit=-1
          coverage: pcov


      - name: Configure Symfony
        run: composer config extra.symfony.require "${{ matrix.symfony }}"

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Cache dependencies"
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-

      - name: "Install highest dependencies"
        run: |
          composer global require php-coveralls/php-coveralls
          composer update --no-interaction --no-progress --no-suggest

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          SYMFONY_PHPUNIT_VERSION: "12"
        run: vendor/bin/phpunit --coverage-clover build/reports/clover.xml

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          php-coveralls --coverage_clover=build/reports/clover.xml --json_path=build/reports/coveralls-upload.json -v
        continue-on-error: true
